# Generated by Django 4.1.2 on 2022-11-12 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.FloatField()),
                ('comentarios', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('expediente', models.CharField(max_length=200)),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.procedencia')),
                ('programaeducativo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('cumplio', models.BooleanField(default='0')),
                ('costo', models.FloatField(blank=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.aula')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.cliente')),
            ],
        ),
    ]
