# Generated by Django 4.1.2 on 2022-10-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('procedencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('cumplio', models.BooleanField()),
                ('costo', models.FloatField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.aula')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.cliente')),
            ],
        ),
    ]
