# Generated by Django 4.1.2 on 2022-11-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapias', '0002_cita_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='cliente',
            new_name='paciente',
        ),
    ]
