# Generated by Django 4.1.2 on 2022-10-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapias', '0002_alter_cita_fecha_alter_cita_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.procedencia'),
        ),
    ]
