# Generated by Django 4.1.2 on 2022-11-13 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisioterapias', '0003_rename_cliente_paciente_rename_cliente_cita_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
