# Generated by Django 4.1.2 on 2022-11-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapias', '0003_procedencia_remove_cita_hora_alter_cita_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='cumplio',
            field=models.BooleanField(default='0'),
        ),
    ]
