# Generated by Django 4.1.2 on 2022-11-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisioterapias', '0004_cita_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='expediente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='procedencia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fisioterapias.procedencia'),
        ),
    ]
